### ISSUE TITLE
why tokio flush stdout but others not flush

### ISSUE THREAD

**Issue by Sherlock-Holo** [ZettaScaleLabs/rust-async-net-eval#4]
https://github.com/ZettaScaleLabs/rust-async-net-eval/blob/master/tokio-ping-tcp/src/main.rs#L62

here tokio flush the stdout

**Comment by gabrik** [comment]
It is because otherwise when redirecting the output to a file it does not print anything.

Also, that `flush()` is "harmless" because it is outside of the timing part that happens only between lines 41 and 46.

I'll try again if the redirection works, but my guess is that it will not have any impact on the actual numbers.

**Comment by gabrik** [comment]
@Sherlock-Holo we changed the way the results are reported, to avoid context switches, the new version is in https://github.com/ZettaScaleLabs/rust-async-net-eval/tree/no-print 

We are running the networked tests and then we will merge, anyway we have the tests for the localhost and there is no difference.

[local-after.pdf](https://github.com/ZettaScaleLabs/rust-async-net-eval/files/8638629/local-after.pdf)

**Comment by gabrik** [comment]
Fixed by #5
